version: '3.2'

services:
  crond:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cron-sendemail:latest
    hostname: cron-sendemail
    container_name: cron-sendemail
    restart: always

